services:
  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./mongodb/init/:/docker-entrypoint-initdb.d/init/
      - ./mongodb/tls/:/data/tls/
      - ./mongodb/mongod.conf:/etc/mongod.conf
    ports:
      - 27017:27017
    # entrypoint: tail -f /dev/null
    command:
      - --config
      - /etc/mongod.conf
      - --replSet
      - rs0
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet --tls --tlsAllowInvalidCertificates
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongodb-init:
    image: mongo:8.0.4
    container_name: mongodb-init
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./mongodb/scripts/:/data/scripts/
      - ./mongodb/document/:/data/document/
    entrypoint:
      - /bin/bash
      - -exc
      - |
        bash /data/scripts/init-replicaset.sh
        bash /data/scripts/import.sh
    restart: on-failure
        
  mongodb-express:
    image: mongo-express:1.0.2
    container_name: mongodb-express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    depends_on:
      mongodb-init:
        condition: service_completed_successfully
    ports:
      - 8081:8081
    restart: always
