definitions:
  model.GetUserResponse:
    properties:
      display_name:
        example: Scott Li
        type: string
      email:
        example: example@mediation-platform.com
        type: string
      phone_number:
        example: "+886987654321"
        type: string
      photo_url:
        example: https://example.com/photo.jpg
        type: string
      user_id:
        example: "1234567890"
        type: string
    type: object
  model.MessageResponse:
    properties:
      message:
        example: ok
        type: string
    type: object
info:
  contact: {}
paths:
  /health/liveness:
    get:
      description: Liveness check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.MessageResponse'
      summary: Liveness check
      tags:
      - health
  /health/readiness:
    get:
      description: Readiness check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.MessageResponse'
      summary: Readiness check
      tags:
      - health
  /v1/user/{user_id}:
    get:
      description: Get user info
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetUserResponse'
      security:
      - TokenAuth: []
      summary: Get user
      tags:
      - user
securityDefinitions:
  TokenAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
