
name: PR Body Generator

on:
  pull_request:

permissions:
  contents: read
  repository-projects: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate PR Body
        uses: jbrocher/auto-pr-body-generator@v0.2.2
        with:
          OPENAI_API_KEY: ${{ secrets.PR_AGENT_OPENAI_API_KEY }}
